# Generated by Django 5.0.3 on 2024-03-21 08:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0003_alter_user_managers"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="otp",
            field=models.CharField(default=0, max_length=4),
            preserve_default=False,
        ),
    ]
