# Generated by Django 5.1.2 on 2024-10-22 10:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0004_user_otp"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="password",
            field=models.CharField(max_length=100),
        ),
    ]
