# Generated by Django 5.1.2 on 2024-10-22 10:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0005_alter_user_password"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(blank=True, default="user", max_length=20),
        ),
    ]
